// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ManualTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void manualTest() {
    driver.get("http://54.39.99.59/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.linkText("About")).click();
    driver.findElement(By.linkText("Our Teachers")).click();
    driver.findElement(By.linkText("Courses")).click();
    driver.findElement(By.linkText("Reviews")).click();
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.linkText("+65 2244 1100")).click();
    driver.findElement(By.cssSelector(".col-md-4:nth-child(1) > .feature-thumb > span")).click();
    driver.findElement(By.cssSelector(".team-thumb li:nth-child(3) > .fa-instagram")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > .fa-google")).click();
    driver.findElement(By.cssSelector(".col-md-3:nth-child(4) .fa-twitter")).click();
    driver.findElement(By.cssSelector(".fa-behance")).click();
    driver.findElement(By.cssSelector(".owl-item:nth-child(7) .courses-top .img-responsive")).click();
    driver.findElement(By.linkText("Summer Kids")).click();
    driver.findElement(By.cssSelector(".owl-item:nth-child(9) .courses-price span")).click();
    driver.findElement(By.id("team")).click();
    driver.findElement(By.name("full name")).click();
    driver.findElement(By.name("full name")).sendKeys("joan");
    driver.findElement(By.name("email")).sendKeys("joano@com");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.id("form-submit")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("capricornio@esuncolor");
    driver.findElement(By.name("submit")).click();
  }
}
